import { TouristSpot } from '../lib/tourist-data';

export const touristSpots: TouristSpot[] = [
  // 江ノ島エリア
  {
    id: "enoshima-shrine",
    name: "江島神社",
    description: "縁結びで有名な神社。海を望む絶景スポットとして人気",
    area: "enoshima",
    category: "shrine",
    tags: ["縁結び", "絶景", "歴史", "パワースポット", "女性人気", "写真映え"],
    duration: 60,
    difficulty: "moderate",
    coordinates: { lat: 35.2993, lng: 139.4804 },
    openHours: "8:30-17:00",
    entrance_fee: 0,
    image: "/placeholder-718sk.png",
    tips: ["エスカーを利用すると楽に登れます", "夕日の時間帯がおすすめ", "御朱印は3つの宮で異なります"],
    coupons: [
      {
        id: "enoshima-shrine-coupon-1",
        title: "エスカー割引券",
        description: "エスカー利用料金10%OFF",
        discount: "10%OFF",
        validUntil: "2024-12-31",
        spotId: "enoshima-shrine",
      },
    ],
  },
  {
    id: "enoshima-sea-candle",
    name: "江ノ島シーキャンドル",
    description: "展望台からの360度パノラマビューが楽しめる灯台",
    area: "enoshima",
    category: "nature",
    tags: ["絶景", "展望台", "夜景", "デート", "写真映え", "イルミネーション"],
    duration: 45,
    difficulty: "easy",
    coordinates: { lat: 35.2985, lng: 139.4798 },
    openHours: "9:00-20:00",
    entrance_fee: 500,
    image: "/placeholder-kuqhr.png",
    tips: [
      "夕日と夜景の両方が楽しめる時間帯がおすすめ",
      "冬季はイルミネーションが美しい",
      "サムエル・コッキング苑とセット券がお得",
    ],
    coupons: [
      {
        id: "sea-candle-coupon-1",
        title: "セット券割引",
        description: "シーキャンドル＋サムエル・コッキング苑セット券100円OFF",
        discount: "100円OFF",
        validUntil: "2024-12-31",
        spotId: "enoshima-sea-candle",
      },
    ],
  },
  {
    id: "enoshima-aquarium",
    name: "新江ノ島水族館",
    description: "相模湾の海をテーマにした水族館。イルカショーが人気",
    area: "enoshima",
    category: "activity",
    tags: ["水族館", "イルカショー", "ファミリー", "雨の日OK", "子供向け", "カップル"],
    duration: 120,
    difficulty: "easy",
    coordinates: { lat: 35.3067, lng: 139.4804 },
    openHours: "9:00-17:00",
    entrance_fee: 2500,
    image: "/placeholder-mznnd.png",
    tips: ["イルカショーの時間を事前にチェック", "平日は比較的空いています", "タッチプールで海の生き物と触れ合えます"],
    coupons: [
      {
        id: "aquarium-coupon-1",
        title: "入場料割引券",
        description: "大人入場料200円OFF",
        discount: "200円OFF",
        validUntil: "2024-12-31",
        spotId: "enoshima-aquarium",
      },
    ],
  },
  {
    id: "enoshima-beach",
    name: "片瀬東浜海水浴場",
    description: "江ノ島に最も近い海水浴場。マリンスポーツも楽しめる",
    area: "enoshima",
    category: "nature",
    tags: ["海水浴", "マリンスポーツ", "夏限定", "アクティブ", "若者向け", "サーフィン"],
    duration: 180,
    difficulty: "easy",
    coordinates: { lat: 35.3089, lng: 139.4823 },
    openHours: "9:00-17:00（夏季のみ）",
    entrance_fee: 0,
    image: "/placeholder-kx9a3.png",
    tips: ["夏季（7-8月）のみ海水浴場として開放", "サーフィンは年中可能", "海の家でグルメも楽しめます"],
    coupons: [],
  },
  // 鎌倉エリア
  {
    id: "kamakura-daibutsu",
    name: "鎌倉大仏（高徳院）",
    description: "高さ13.35mの青銅製阿弥陀如来坐像。鎌倉のシンボル",
    area: "kamakura",
    category: "temple",
    tags: ["大仏", "歴史", "文化財", "写真映え", "定番", "外国人人気"],
    duration: 45,
    difficulty: "easy",
    coordinates: { lat: 35.3167, lng: 139.5358 },
    openHours: "8:00-17:30",
    entrance_fee: 300,
    image: "/----.jpg",
    tips: [
      "大仏の胎内に入ることができます（別料金）",
      "朝の時間帯は比較的空いています",
      "長谷駅から徒歩7分とアクセス良好",
    ],
    coupons: [
      {
        id: "daibutsu-coupon-1",
        title: "胎内拝観割引券",
        description: "大仏胎内拝観料50円OFF",
        discount: "50円OFF",
        validUntil: "2024-12-31",
        spotId: "kamakura-daibutsu",
      },
    ],
  },
  {
    id: "hasedera-temple",
    name: "長谷寺",
    description: "十一面観音菩薩で有名な寺院。四季の花々が美しい",
    area: "kamakura",
    category: "temple",
    tags: ["観音様", "花", "庭園", "紅葉", "あじさい", "女性人気", "癒し"],
    duration: 60,
    difficulty: "easy",
    coordinates: { lat: 35.3125, lng: 139.5342 },
    openHours: "8:00-17:00",
    entrance_fee: 400,
    image: "/placeholder-8atai.png",
    tips: ["6月のあじさいシーズンが特に美しい", "見晴台からの景色は絶景", "御朱印は複数種類あります"],
    coupons: [
      {
        id: "hasedera-coupon-1",
        title: "拝観料割引券",
        description: "拝観料50円OFF",
        discount: "50円OFF",
        validUntil: "2024-12-31",
        spotId: "hasedera-temple",
      },
    ],
  },
  {
    id: "tsurugaoka-hachimangu",
    name: "鶴岡八幡宮",
    description: "鎌倉の中心に位置する八幡宮。源頼朝ゆかりの神社",
    area: "kamakura",
    category: "shrine",
    tags: ["八幡宮", "源頼朝", "歴史", "武士", "桜", "初詣", "定番"],
    duration: 75,
    difficulty: "easy",
    coordinates: { lat: 35.3258, lng: 139.5563 },
    openHours: "6:00-20:30",
    entrance_fee: 0,
    image: "/-----.jpg",
    tips: ["段葛の桜並木は春の名所", "宝物殿では貴重な文化財を展示", "小町通りからのアクセスが便利"],
    coupons: [
      {
        id: "tsurugaoka-coupon-1",
        title: "宝物殿割引券",
        description: "宝物殿入館料100円OFF",
        discount: "100円OFF",
        validUntil: "2024-12-31",
        spotId: "tsurugaoka-hachimangu",
      },
    ],
  },
  {
    id: "komachi-street",
    name: "小町通り",
    description: "鎌倉駅から鶴岡八幡宮へ続く商店街。グルメとお土産の宝庫",
    area: "kamakura",
    category: "shopping",
    tags: ["商店街", "グルメ", "お土産", "食べ歩き", "若者向け", "インスタ映え"],
    duration: 90,
    difficulty: "easy",
    coordinates: { lat: 35.3194, lng: 139.5508 },
    openHours: "10:00-18:00（店舗により異なる）",
    entrance_fee: 0,
    image: "/------.jpg",
    tips: ["鎌倉コロッケや抹茶アイスが人気", "平日の方が歩きやすい", "お土産は種類豊富で選び放題"],
    coupons: [
      {
        id: "komachi-coupon-1",
        title: "食べ歩きクーポン",
        description: "対象店舗で使える100円割引券",
        discount: "100円OFF",
        validUntil: "2024-12-31",
        spotId: "komachi-street",
      },
    ],
  },
  {
    id: "hokokuji-temple",
    name: "報国寺（竹の庭）",
    description: "美しい竹林で有名な禅寺。竹の庭で抹茶を楽しめる",
    area: "kamakura",
    category: "temple",
    tags: ["竹林", "抹茶", "禅", "癒し", "写真映え", "静寂", "大人向け"],
    duration: 60,
    difficulty: "easy",
    coordinates: { lat: 35.3147, lng: 139.5675 },
    openHours: "9:00-16:00",
    entrance_fee: 300,
    image: "/------.jpg",
    tips: ["竹の庭での抹茶体験がおすすめ（別料金）", "朝の時間帯は特に静寂で美しい", "写真撮影は指定エリアのみ"],
    coupons: [
      {
        id: "hokokuji-coupon-1",
        title: "抹茶セット割引券",
        description: "竹の庭抹茶セット100円OFF",
        discount: "100円OFF",
        validUntil: "2024-12-31",
        spotId: "hokokuji-temple",
      },
    ],
  },
]